services:
  db:
    image: mysql:8.0.41
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    container_name: ${DB_HOST}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost --user=root --password=${DB_PASSWORD}
    networks:
      booking_service:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      booking_service:


networks:
  booking_service:
volumes:
  db_data: